# Docker Compose configuration for swingTrader application
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/swingtrader
      - SECRET_KEY=${SECRET_KEY:-developmentsecretkey}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    command: sh -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    expose:
      - "5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=swingtrader
      - POSTGRES_DB=swingtrader
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
